config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  get '/pics' => 'application#pics.html.erb'
  get '/6-month-review' => 'application#6-month-review.html.erb'
  get '/12-month-review' => 'application#12-month-review.html.erb'
  get '/18-month-review' => 'application#18-month-review.html.erb'
  get '/investmentTracker' => 'investment_tracker#index'
  get '/investmentTracker/reset' => 'investment_tracker#destroy'
  get '/investmentTracker/new' => 'investment_tracker#new'
  post '/investmentTracker' => 'investment_tracker#create'
  post '/mail' => 'welcome#mail'
  
  resources :articles
  resources :transactions

  resources :transactions do
    collection { post :import }
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  logger = Logger.new(STDOUT)

  require 'date'
  def index
    logger.info("Transactions Controller - index")
    # @transactions = Transaction.all
    @investments = Investment.all
    @holdings = Holdings.all
    @totals = Totals.all
    @totalToday = Totals.order('totals.date DESC').first
  end

  def show
    puts "Transactions Controller - show"
    @transaction = Transaction.find(params[:id])
    begin
      @investment = Investment.find(@transaction.symbol)
    rescue ActiveRecord::RecordNotFound
      @investment = Investment.new(@transaction)
      @investment.save
    end
  end

  def new
    @transaction = Transaction.new

  end

  def create
    @transaction = Transaction.new(transaction_params)
    if @transaction.save
      if Investment.exists?(@transaction.symbol)
        @investment = Investment.find(@transaction.symbol)
        Holdings.updateQuantityOfStock(@transaction)
      else
        @investment = Investment.build(@transaction)
        if @investment.save
          Holdings.populateHoldings(@transaction)
          Holdings.updateTotals
        else
          raise "NEW INVESTMENT FAILED"
        end
      end
      redirect_to transactions_path
    else
      render 'new'
    end
  end

  def update
    @transaction = Transaction.find(params[:id])
    if @transaction.update(transaction_params)
      redirect_to @transaction
    else
      render 'edit'
    end
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    redirect_to transactions_path
  end

  def import
    Transaction.import(params[:file])
    redirect_to investmentTracker_url, notice: "Transactions imported."
  end

  private
  def transaction_params
    params.require(:transaction).permit(:symbol, :quantity, :price, :action, :commission, :date)
  end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Transactions</title>
</head>
<body>

<!--<h1 id="title">Investment History</h1>-->


<div class="container">
  <% unless @totalToday.nil? %>
      <div class="row">
        <p class="col-xs-3" >Total invested: $<%= @totalToday.getTotalInvested %></p>
        <p class="col-xs-3" >Total value: $<%= @totalToday.getTotalValue%></p>
        <p class="col-xs-3" >+<%= @totalToday.percentageChange %>%</p>
      </div>
  <% end %>
</div>

<div class="graph" id="line-chart">
  <%= line_chart [ { name: "Total Value", data: @totals.where("total_value > 0").group(:date).sum(:total_value)},
                   { name: "Total Invested", data: @totals.where("total_value > 0").group(:date).sum(:total_invested)},
                   { name: "Percent Change", data: @totals.where("total_value > 0").group(:date).sum(:percentage_change)}],
                   { library: {
                             title: "Value Grown Over Time", titlePosition: "out",
                             crosshair: { trigger: 'focus', orientation: 'both' },
                             explorer: { actions: ['dragToZoom', 'rightClickToReset'] , keepInBounds: true, maxZoomIn: 0.1, maxZoomOut: 1},
                             curveType: "none",
                             pointSize: 0,
                             width: 800,
                             height: 500,
                             vAxes: { 0 => {logScale: false, title: "Dollars", ticks: [{v: 0, f: "0"}, {v: 5000, f: "$5000"}, {v: 10000, f: "$10000"}, {v: 15000, f: "$15000"}, {v: 20000, f: "$20000"}, {v: 25000, f: "$25000"}, {v: 30000, f: "$30000"}]},
                                      1 => {logScale: false, title: "Percent Change", ticks: [{v:-20, f: '-20%'}, {v:0, f: '0'}, {v:20, f: '20%'}, {v:40, f: '40%'}, {v:60, f: '60%'}, {v:80, f: '80%'}, {v:100, f: '100%'}]} },
                             series: { 0 => {targetAxisIndex: 0 }, 1 => {targetAxisIndex: 0 }, 2 => {targetAxisIndex: 1} } } } %>
</div>

<div class="graph" id="pie-chart">
<%= pie_chart @investments.group(:symbol).sum(:total_value) ,
              {library: {
                  title: "Investment Allocation",
                  height: 300, width: 500, is3D: 'true', sliceVisibilityThreshold: 0}}%>
</div>

<div id="investments">
  <h2>Investments</h2>
  <table class="transaction-table">
    <tr>
      <th>Symbol</th>
      <th>Quantity</th>
      <th>Average Purchase Price</th>
      <th>Current Price</th>
      <th>Value</th>
      <th>Percent change</th>
    </tr>
    <% @investments.each do |investment| %>
        <tr>
          <td><%= investment.symbol %></td>
          <td><%= investment.quantity %></td>
          <td>$<%= investment.avg_cost %></td>
          <td>$<%= investment.get_stock_price %></td>
          <td>$<%= investment.value %></td>
          <td><%= investment.percent_change %>%</td>
        </tr>
    <% end %>
  </table>
</div>
<div id="add-actions">
  <div id="new-action"><%= link_to 'New transaction', new_transaction_path %></div>
  <div id="import-csv">
    <h3>Import a CSV File</h3>
    <%= form_tag import_transactions_path, multipart: true do %>
        <%= file_field_tag :file %>
        <%= submit_tag "Import CSV" %>
    <% end %>
  </div>
</div>

</body>
</html>

app/views/transactions/new.html.erb
<h1>Add a new transaction of a stock</h1>
<div id="transaction-form-outer">
    <div id="transaction-form-inner">
        <%= form_for :transaction, url: transactions_path do |f| %>
            <p>
              <%= f.label :symbol %>
              <%= f.text_field :symbol %>
            </p>

            <p>
              <%= f.label :quantity %>
              <%= f.text_field :quantity %>
            </p>

            <p>
              <%= f.label :price %>
              <%= f.text_field :price %>
            </p>

            <p>
              <%= f.select :action, [['Buy','buy'],['Sell','sell']] %>
            </p>

            <p>
              <%= date_select("transaction", "date", order: [:month, :day, :year]) %>
            </p>

            <p>
              <%= f.submit %>
            </p>
        <% end %>
    </div>
</div>

<div id="import-csv">
    <h3>Import a CSV File</h3>
    <%= form_tag import_transactions_path, multipart: true do %>
        <%= file_field_tag :file %>
        <%= submit_tag "Import CSV" %>
    <% end %>
</div>

app/views/transactions/show.html.erb
<p>
  <strong>Ticker Symbol:</strong>
  <%= @transaction.symbol %>
</p>

<p>
  <strong>Purchase price:</strong>
  <%= @transaction.price %>
</p>

<p>
  <strong>Current price:</strong>
  <%= @investment.get_stock_price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @investment.quantity %>
</p>

<%= link_to "Back", transactions_path %>
<%= link_to 'Edit', edit_transaction_path(@transaction) %>
<%= link_to 'Destroy', transaction_path(@transaction),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>